name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['2.7']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Configure git for testing
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"
          git config --global core.autocrlf false

      - name: Run unit tests
        run: rake unit_tests
